
# need=['',95,'']
# for s in range(need):
# for s in need:
a=int(input("enter the dob "))
if (a ==ord("") or a ==ord("") or a ==ord('ߎ')):
# if a==ord('ߎ'):
    # print(a)
    # print("your age",ord(''))
    #///////////////
    # def age_calculator(current_year,birth_year):
    #  age = current_year - birth_year
    #  print("The age of the person in years is",age,"years")
    # age_calculator(2023,1995)
    # age_calculator('ߨ,ߎ')
#//////////////
    t=[72,65,80,80,89,95,66,73,82,84,72,95,68,65,89]
    for r in t:
        print(chr(r), end=' ')
    print('\n')
    x = ord("ߨ")
    s = ord("ߎ")
    f=x-s
    print("Congratulations your age is ",f)
    print('\n')
    import datetime
    d=datetime.datetime.now() 
    m=d.strftime("%b")            #%b,%B,%m,%y,%Y,%H,%I,%p,%M
    print(m,'-',d)
    # print(d)
    print('\n')
else:
    print("Pl enter the correct DOB")
    # print(chr(a),end=' ') 
#    if a==ord(95):
#     if a==ord(''):
                          #'','_',
# if a== ord("@"):
    # print(a)
# f=33
# print(chr(f))
    
#     my_list = []
# # Get input from the user and append it to the list
# user_input = input("Enter a value: ")
# my_list = my_list + [user_input]
    
#     for i in range(32, 128): 
#         print(chr(i), end=' ') 5_7
#     if (i - 1) % 10 == 0: 
#         print() 
 
# print() 
# x = ord("@")

# print(x)
    