# a=int(input("Enter the ASCII Value"))
# for a in range(0,20,("s")):
#     print(a)
s=78
print(chr(s), end ='')
s=73
print(chr(s), end =' ')
s=84
print(chr(s), end =' ')
s=72
print(chr(s), end =' ')
s=69
print(chr(s), end =' ')
s=69
print(chr(s), end =' ')
s=83
print(chr(s), end =' ')
s=72
print(chr(s), end =' ')
s=65
print(chr(s), end =' ')
s=82
print(chr(s), end =' ')
s=696868
print(chr(s), end =' ')
s=68
print(chr(s), end =' ')
s=68
print(chr(s), end =' ')
s=89
print(chr(s), end =' ')